=== cybersonic/CFMLEdit/org.cfeclipse.cfmledit.dictionaries/dictionary/dictionary.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
	targetNamespace="http://www.cfeclipse.org/version1/dictionary"
	xmlns="http://www.cfeclipse.org/version1/dictionary"
>
	<!-- root element -->
	<xs:element name="dictionary">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="tags" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="functions" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="scopes" minOccurs="0" maxOccurs="1"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<!-- second level elements (main groups) -->
	<xs:element name="tags">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="tag" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="functions">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="function" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="scopes">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="scope" minOccurs="0" maxOccurs="unbounded" />	
			</xs:sequence>		
		</xs:complexType>
	</xs:element>
	
	<!-- single items (third level stuff) -->
	<xs:element name="tag">
		<xs:complexType>
			
			<xs:sequence>
				<xs:element ref="help"/>
				<xs:element ref="parameter" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
			
			<xs:attribute name="creator" type="xs:string" />
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="single" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="true"/>
						<xs:enumeration value="false"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			
			<xs:attribute name="xmlstyle" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="true"/>
						<xs:enumeration value="false"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			
			<xs:attribute name="hybrid" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="true"/>
						<xs:enumeration value="false"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			
			<xs:attribute name="allowanyattribute" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="true"/>
						<xs:enumeration value="false"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			
		</xs:complexType>
	</xs:element>
	
	<xs:element name="function">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="help"/>
				<xs:element ref="parameter" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
			
			<xs:attribute name="creator" type="xs:string" />
			<xs:attribute name="name" type="xs:string" use="required"/>
			
			<xs:attribute name="returns" use="required">
				<xs:simpleType>
					<xs:restriction base="cfbasetypes"/>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="scope">
		<xs:complexType>
			<xs:attribute name="value" />
		</xs:complexType>
	</xs:element>
	
	<!-- mostly arguements and modifiers for the third level items. these further
		define the page level items -->
	<xs:element name="parameter">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="help"/>
				<xs:element ref="values" minOccurs="0" />
				<xs:element ref="triggers" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
			
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="default" type="xs:string" />
			
			<xs:attribute name="type" use="required">
				<xs:simpleType>
					<xs:restriction base="cfbasetypes"/>
				</xs:simpleType>
			</xs:attribute>
			
			<xs:attribute name="required" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="true"/>
						<xs:enumeration value="false"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			
		</xs:complexType>
	</xs:element>
	
	<!-- values that a parameter may have (function or tag) -->	
	<xs:element name="values">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="value"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="value">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="option" type="xs:string" use="required"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	
	<!-- by default all parameters will show for a tag / function unless there are
		triggers applied. Then the rules set using selectedValue will govern if 
		a parameter will show -->
	<xs:element name="triggers">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="selectedValue" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="selectedValue">
		<xs:complexType>
			<!-- this references an attribute in the parent tag and when... -->
			<xs:attribute name="attributeName" use="required"/>
			<!-- its value is what is in here this trigger applies -->
			<xs:attribute name="value" use="required"/>
			<!-- marks the parameter as required or optional -->
			<xs:attribute name="required" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="true"/>
						<xs:enumeration value="false"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			
			<xs:attribute name="index" type="xs:integer" use="optional" />
		</xs:complexType>
	</xs:element>
	
	
	<!-- misc stuff -->
	<xs:element name="help" type="xs:string"/>
	
	<xs:simpleType name="cfbasetypes">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Any" />
			<xs:enumeration value="Array" />
			<xs:enumeration value="Binary" />
			<xs:enumeration value="boolean" />
			<xs:enumeration value="char" />
			<xs:enumeration value="DateTime" />
			<xs:enumeration value="Function" />
			<xs:enumeration value="ISODateTime" />
			<xs:enumeration value="Node" />
			<xs:enumeration value="Numeric" />
			<xs:enumeration value="Object" />
			<xs:enumeration value="ODBCDate" />
			<xs:enumeration value="ODBCDateTime" />
			<xs:enumeration value="ODBCTime" />
			<xs:enumeration value="Query" />
			<xs:enumeration value="QueryColumn" />
			<xs:enumeration value="Regex" />
			<xs:enumeration value="String" />
			<xs:enumeration value="Struct" />
			<xs:enumeration value="Timespan" />
			<xs:enumeration value="URL" />
			<xs:enumeration value="UUID" />
			<xs:enumeration value="void" />
			<xs:enumeration value="xml" />
			<xs:enumeration value="variableName" />
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== cybersonic/CFMLEdit/org.cfeclipse.cfmledit.dictionaries/dictionary/js.xml
<?xml version="1.0" ?>
<!--
	Note:
	this file will be over written when you upgrade the plugin, but the file 
	spec shouldn't change without notice so you can just over write this file 
	if you wish.
-->
<dictionary xmlns="http://www.cfeclipse.org/version1/dictionary"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.cfeclipse.org/version1/dictionary http://cfeclipse.tigris.org/version1/dictionary/dictionary.xsd"
>
	<functions>
		<function name="eval" returns="Object">
			<help><![CDATA[
			]]></help>
			<parameter name="codeString" type="String" required="true">
				<help><![CDATA[
				]]></help>
			</parameter>
		</function>

		<function name="isFinite" returns="boolean">
			<help><![CDATA[
			]]></help>
			<parameter name="testnumber" type="Numeric" required="true">
				<help><![CDATA[
				]]></help>
			</parameter>
		</function>

		<function name="isNaN" returns="boolean">
			<help><![CDATA[
			]]></help>
			<parameter name="testvalue" type="Object" required="true">
				<help><![CDATA[
				]]></help>
			</parameter>
		</function>
	
		<function name="Number" returns="Numeric">
			<help><![CDATA[
			]]></help>
			<parameter name="obj" type="Object" required="true">
				<help><![CDATA[
				]]></help>
			</parameter>
		</function>
	
		<function name="parseFloat" returns="Numeric">
			<help><![CDATA[
			]]></help>
			<parameter name="str" type="String" required="true">
				<help><![CDATA[
				]]></help>
			</parameter>
		</function>
	
		<function name="parseInt" returns="Numeric">
			<help><![CDATA[
				parses a string and returns a javascript integer
			]]></help>
			<parameter name="str" type="String" required="true">
				<help><![CDATA[
					String to parse
				]]></help>
			</parameter>
			<parameter name="radix" type="Numeric" required="false">
				<help><![CDATA[
					The base to use. I.e. 16, 8, 10 default 10
				]]></help>
			</parameter>
		</function>
	
		<function name="String" returns="boolean">
			<help><![CDATA[
			]]></help>
			<parameter name="obj" type="Object" required="true">
				<help><![CDATA[
				]]></help>
			</parameter>
		</function>

		<function name="alert" returns="void">
			<help><![CDATA[
				Alert box
			]]></help>
			<parameter name="str" type="String" required="true">
				<help><![CDATA[
					the dialog box text
				]]></help>
			</parameter>
		</function>
	
		<function name="confirm" returns="boolean">
			<help><![CDATA[
				Confirm dialog box
			]]></help>
			<parameter name="str" type="String" required="true">
				<help><![CDATA[
					the dialog box text
				]]></help>
			</parameter>
		</function>

		<function name="unescape" returns="String">
			<help><![CDATA[
				Unescapes the passed string so that is can be passed in a url
			]]></help>
			<parameter name="encodedString" type="String" required="true">
				<help><![CDATA[
					The String to unescape
				]]></help>
			</parameter>
		</function>

		<function name="escape" returns="String">
			<help><![CDATA[
				Escapes the passed string so that is can be passed in a url
			]]></help>
			<parameter name="str" type="String" required="true">
				<help><![CDATA[
					The String to escape
				]]></help>
			</parameter>
		</function>
		
		<function name="typeof" returns="String">
			<help><![CDATA[
				returns one of the following strings:
				* number
				* string
				* boolean
				* object
				* function
				* undefined
			]]></help>
			<parameter name="object" type="Object" required="true">
				<help><![CDATA[
					The object who's type is in question
				]]></help>
			</parameter>
		</function>
	</functions>
</dictionary>
